version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.29.0
    container_name: pocketbase
    restart: unless-stopped
    command:
    environment:
    ports:
      - "8090:8090"
    volumes:
      - /pocketbase-service/pb_data:/pb_data
      - /pocketbase-service/pb_public:/pb_public
      - /pocketbase-service/pb_hooks:/pb_hooks
      - /pocketbase-service/pb_migrations:/pb_hooks
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  mailin-service:
    container_name: mailin-service
    build: ./mailin-service
    ports:
      - "25:1025"
    volumes:


