version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.29.0
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase-service/pb_hooks:/pb_hooks
      - ./pocketbase-service/pb_migrations:/pb_migrations
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  mailin-service:
    container_name: mailin-service
    build: ./mailin-service
    ports:
      - "25:1025"
    depends_on:
      pocketbase:
        condition: service_healthy
        restart: true

